### ISSUE TITLE
isSocketAllowedBySecurityPolicy start : device null 

### ISSUE THREAD

**Issue by alizubidy** [infiniteloopcloud/simpleblue#7]
Hello,

I've been facing issues with the Android 12, the example provided works perfectly with any other android version, but when running on Samsung devices with Android 12 (And Oppo devices as well), I've been getting stuck at 

`D/SimplebluePlugin(16646): android call received: "connect"
D/SimplebluePlugin(16646): Connecting to 64:A2:F9:F5:8A:33
D/BluetoothUtils(16646): isSocketAllowedBySecurityPolicy start : device null
I/BluetoothSocket(16646): connect() for device 64A2F9_3 called by pid: 16646`

It connects to the selected device, then disconnects instantly, or just never connects

Any suggestions would be highly appreciated

Sincerely

P.S : All permissions have been provided from the "Settings" page, and the app & package works perfectly with other android version

**Comment by PumpkinSeed** [comment]
Hi,

Sorry for the late answer it took some time to find devices with Android 12. :)

So we couldn't replicate the issue (tested in Samsung and Xiaomi devices). @jkirtyan is our expert in that field, so if you can provide more details on what device have you tried and what was on the other end, where you tried to connect, etc.

What I can imagine that the two device's Bluetooth profile or supported profiles are different. I usually facing with similar issue when connecting to embedded systems and there is a profile mismatch.

Tested devices:
- Samsung A71 SM-A715F/DS

**Comment by PumpkinSeed** [comment]
Close the issue, if you still have any additional to it, please reopen it.
